# Generated by Django 3.2.5 on 2021-08-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_code', models.CharField(max_length=10)),
                ('course_trainer', models.CharField(max_length=30)),
                ('course_schedule', models.FileField(blank='True', upload_to='Uploads')),
                ('syllabus', models.TextField(max_length=300)),
                ('course_duration', models.CharField(max_length=30)),
                ('time_in_hours', models.DurationField()),
            ],
        ),
    ]
