# Generated by Django 3.2.6 on 2021-08-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_trainer_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='contract',
            field=models.FileField(blank='True', upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
