# Generated by Django 3.2.5 on 2021-08-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=30)),
                ('event_name', models.CharField(max_length=30)),
                ('event_id', models.CharField(max_length=30)),
                ('event_duration', models.DurationField()),
                ('event_planner', models.CharField(max_length=30)),
                ('event_approved_by', models.CharField(max_length=30)),
                ('event_participants', models.TextField(max_length=400)),
                ('event_date_and_time', models.DateField()),
            ],
        ),
    ]
