# Generated by Django 3.2.6 on 2021-08-22 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='event_date_and_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
