# Generated by Django 3.2.6 on 2021-08-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_calendar', '0002_alter_calendar_event_date_and_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
