# Generated by Django 3.2.6 on 2021-08-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_calendar', '0003_auto_20210824_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='AkiraChix', max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
