# Generated by Django 3.2.6 on 2021-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210805_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='languages',
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('A', 'Arabic'), ('E', 'English'), ('F', 'French'), ('K', 'Kiswahili'), ('Ki', 'Kinyarwanda')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[], max_length=10, null=True),
        ),
    ]
