# Generated by Django 3.2.6 on 2021-08-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210809_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
